// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_KOState","status":true,"description":"This plugin enables you to use alternate KO states","parameters":{}}
];
